import { SiteHeader } from '@/components/site-header';

export default function AboutPage() {
  return (
    <>
      <SiteHeader />
      <main className="container py-8 max-w-3xl">
        <h1 className="text-2xl font-bold mb-4">About this benchmark</h1>

        <section className="mb-8 space-y-3 text-sm leading-6">
          <p>
            TanzuBench is an open leaderboard of LLMs running on the Tanzu
            GenAI tile. We track speed, accuracy, and scale characteristics across real
            VMware foundations — CPU and GPU, Ollama and vLLM.
          </p>
          <p>
            Unlike cloud-only benchmarks, the same model behaves very differently
            depending on the hardware and engine underneath it. This site surfaces those
            differences as first-class filters.
          </p>
          <p>
            This site is hosted on the <strong>NDC</strong> foundation but displays
            results from every foundation that contributes data (CDC, DEV210, TDC, and
            others). Hosting location is unrelated to data provenance.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-lg font-semibold mb-2">Methodology</h2>
          <p className="text-sm leading-6 mb-3">
            Every result is generated by the <code>bench.sh</code> speed runner or one of
            the accuracy harnesses in <code>tools/</code>. Each run produces a JSON file
            in <code>results/&lt;foundation&gt;/&lt;type&gt;/</code> that must validate
            against <code>schema/result-v1.schema.json</code>.
          </p>
          <p className="text-sm leading-6 mb-3">
            CI runs <code>tools/validate.py</code> on every pull request. Invalid data
            cannot land.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-lg font-semibold mb-2">Test suite</h2>
          <ul className="list-disc list-inside text-sm space-y-1">
            <li>
              <strong>Speed tests</strong>: simple_qa, chat, tool_call_single,
              tool_call_dual, agentic_file_read, multi_step_agentic, code_gen_500,
              long_gen_1000
            </li>
            <li>
              <strong>Accuracy tests</strong>: 5 factual (math, capitals, physics) + 5
              tool calling (single, dual, restraint)
            </li>
            <li>
              <strong>Scale tests</strong>: sequential_consistency, concurrent_load,
              sustained_throughput
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">How to contribute</h2>
          <ol className="list-decimal list-inside text-sm space-y-1 leading-6">
            <li>
              Clone the repo:{' '}
              <code>git clone https://github.com/nkuhn-vmw/tanzubench</code>
            </li>
            <li>
              Run <code>bench.sh --foundation &lt;name&gt; --worker &lt;id&gt;</code> against a
              live worker
            </li>
            <li>
              Commit the generated JSON under{' '}
              <code>results/&lt;foundation&gt;/&lt;type&gt;/</code>
            </li>
            <li>
              Open a pull request — CI validates the schema, the leaderboard rebuilds on
              merge
            </li>
          </ol>
        </section>
      </main>
    </>
  );
}
